name = "SPECreader"
uuid = "0b5e1f4c-4755-4775-bc20-dc99ea6f75ff"
authors = ["spiffmeister <robospiff@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
plotting = ["Makie", "GeometryBasics"]

[compat]
Documenter = "1.16.0"
GeometryBasics = "0.5.10"
HDF5 = "0.17.2"
Literate = "2.20.1"
Makie = "0.22.10"
NonlinearSolve = "4.9.0"
Optim = "1.12.0"
OrdinaryDiffEq = "6.98.0"
StaticArrays = "1.9.13"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[targets]
test = ["Test"]
docs = ["Documenter", "Literate"]
